### ISSUE TITLE
2 Port Can bride is not working even after successful message on programming

### ISSUE THREAD

**Issue by maheshsachintha** [dalathegreat/Nissan-LEAF-Battery-Upgrade#15]
2 Port Can bride is not working even after successful message on programming
![image](https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/assets/58553188/f7afd724-988c-45bd-bafc-9467d0fcdba5)
![image](https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/assets/58553188/bcce6a1b-2cb0-431e-a182-a6e4e5345685)

**Comment by uditha1980** [comment]
Why you say doesn't work....did u connect it to the can bus?...then what happened....
Need more detail of Ur issue to give an answer

**Comment by maheshsachintha** [comment]
> Why you say doesn't work....did u connect it to the can bus?...then what happened.... Need more detail of Ur issue to give an answer

Yes. I connected it to car. But didn't work. 
Car Is 2013 AZE0 Car
Battery is 2018 40 kWh ZE1 battery

**Comment by dalathegreat** [comment]
- How does it not work? 
- Are the battery info visible on the instrument cluster?
   - If not, the bridge itself might be broken 
- Any fault codes active on Leafspy?

**Comment by uditha1980** [comment]
> > Why you say doesn't work....did u connect it to the can bus?...then what happened.... Need more detail of Ur issue to give an answer
> 
> Yes. I connected it to car. But didn't work. Car Is 2013 AZE0 Car Battery is 2018 40 kWh ZE1 battery

Problem with the low cost stlink programmer..
Use a genuine one may avoid most problems..
I compare the two files (before upload and the one in the MCU)...both are not same...but it worked for me...repeat the program session 2 or 3 times....it will ok...may be problem with buffers

**Comment by maheshsachintha** [comment]
> * How does it not work?
> * Are the battery info visible on the instrument cluster?
>   
>   * If not, the bridge itself might be broken
> * Any fault codes active on Leafspy?

Used already paired car
Even initially not worked, it was worked after some programmed tries

**Comment by maheshsachintha** [comment]
Any way to check successfulness program over can bus messages?

**Comment by maheshsachintha** [comment]
I have programmed 8 number of can bridges. And compare srec file using STM32 ST-Utility. Got comparison (same) error as following. Still I haven’t plug this to car. I ll put update once I have checked with car
 
![image](https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/assets/58553188/8f662c36-fd82-4557-81fe-e5d1ea343616)

![image](https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/assets/58553188/9e8b0853-2c41-4132-81a7-d0e7e4d8a419)

 
**Item 1**
00000000	02010000	07060403	44330908
22116655	66774433	01AE4455	02BC0154
**Item 2**
00000000	02010000	07060403	44330908
22116655	66774433	01AE4455	02BC0154
**Item 3**
00000000	02010000	07060403	44330908
22116655	66774433	01AE4455	02BC0154
**Item 4**
00000000	02010000	07060403	44330908
22116655	66774433	01AE4455	02BC0154
**Item 5**
00000000	02010000	07060403	44330908
22116655	66774433	01AE4455	02BC0154
**Item 6**
00000000	02010000	07060403	44330908
22116655	66774433	01AE4455	02BC0154
**Item 7**
00000000	02010000	07060403	44330908
22116655	66774433	01AE4455	02BC0154
**Item 8**
00000000	02010000	07060403	44330908
22116655	66774433	01AE4455	02BC0154

**Comment by maheshsachintha** [comment]
> I have programmed 8 number of can bridges. And compare srec file using STM32 ST-Utility. Got comparison (same) error as following. Still I haven’t plug this to car. I ll put update once I have checked with car
> 
> ![image](https://user-images.githubusercontent.com/58553188/284023093-8f662c36-fd82-4557-81fe-e5d1ea343616.png)
> 
> ![image](https://user-images.githubusercontent.com/58553188/284023098-9e8b0853-2c41-4132-81a7-d0e7e4d8a419.png)
> 
> **Item 1** 00000000 02010000 07060403 44330908 22116655 66774433 01AE4455 02BC0154 **Item 2** 00000000 02010000 07060403 44330908 22116655 66774433 01AE4455 02BC0154 **Item 3** 00000000 02010000 07060403 44330908 22116655 66774433 01AE4455 02BC0154 **Item 4** 00000000 02010000 07060403 44330908 22116655 66774433 01AE4455 02BC0154 **Item 5** 00000000 02010000 07060403 44330908 22116655 66774433 01AE4455 02BC0154 **Item 6** 00000000 02010000 07060403 44330908 22116655 66774433 01AE4455 02BC0154 **Item 7** 00000000 02010000 07060403 44330908 22116655 66774433 01AE4455 02BC0154 **Item 8** 00000000 02010000 07060403 44330908 22116655 66774433 01AE4455 02BC0154

Any way to check this, without plugging to car

**Comment by dalathegreat** [comment]
@maheshsachintha Flashing should only be done with BridgeFlasher.exe, not with STM32 ST-Link Utility.
The diff is due to the copy protection still being present (au8_lock)

You did not explain how the vehicle did not work. Please only flash with BridgeFlasher.exe, and provide the following info:

- How does it not work?
- Are the battery info visible on the instrument cluster?
   - If not, the bridge itself might be broken
- Any fault codes active on Leafspy?

**Comment by Oggioffshore** [comment]
Leaf 2012, 24kwh upgrade to 30Kwh. Experienced error message no at link connected.. Cable was correctly installed. Also had to disable read out protection. Still didn't flash. After upgrade st link with new software it's worked... Just in case other struggling. Never done this earlier. Now I'll try connect it in the car, believe it will work even I have not changed battery? 
![20240222_215921](https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/assets/155973422/8ae7a4aa-0e44-4043-915f-0eaaa67bb52e)
![20240222_214932](https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/assets/155973422/e00f4ef2-a1b2-4982-8f80-84a61bf34f4c)
![20240222_214924](https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/assets/155973422/8ef2f265-d70d-47aa-9480-16d18e2c03a5)
![20240222_220144](https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/assets/155973422/d349686b-9406-4a37-bd90-80d6a47bf9c5)
![20240222_220201](https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/assets/155973422/c812b634-325b-4e53-bab2-e35ddc5b5392)
![20240222_220535](https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/assets/155973422/0a20b495-8c36-4856-bed5-5bea2cd3c8f4)

**Comment by Oggioffshore** [comment]
Battery swop done, been working fine for a few weeks. Guess only drawback is the battery indicator and guess'o meter are working differently... Happy with 30Kwh an extended life for our 2012 Leaf.

**Comment by fopoku2k2** [comment]
> Battery swop done, been working fine for a few weeks. Guess only drawback is the battery indicator and guess'o meter are working differently... Happy with 30Kwh an extended life for our 2012 Leaf.

Need to also do a swap on my 2012. How do I contact you for guidance??

**Comment by Oggioffshore** [comment]
All you need to know are described in this forum. Just read.

**Comment by dalathegreat** [comment]
Closing this, since it is not an issue with the code
