### ISSUE TITLE
I think in the 2 port bridge instructions car can and battery can are reversed

### ISSUE THREAD

**Issue by CrAzYDr1veR** [dalathegreat/Nissan-LEAF-Battery-Upgrade#17]
Following the instructed order nothing works, reversing makes it all ok.
![20231124_152615](https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/assets/47764335/b280fff6-8d9a-40a0-82ae-2a41b0f5d265)

**Comment by dalathegreat** [comment]
Direction does not matter. The bridge passes thru in both directions, and sends based on what is detected on what side.

Maybe you just had a bad connection somewhere initially? Closing this issue as unable to reproduce.

**Comment by CrAzYDr1veR** [comment]
Well i reproduced it twice with soldered wires not connectors, but thanks for explaining that it should work both ways.
