### ISSUE TITLE
battery management 

### ISSUE THREAD

**Issue by hugor25** [dalathegreat/Nissan-LEAF-Battery-Upgrade#20]
Hello
Which software I must install on CAN-Bridge to help my 2015 leaf 24kw **295b04nf0a** to better recharge and balance the cells.
 I'm saving money for switching to a 40kwh battery.

Thanks a lot for the help
from Portugal
Hugo:)

**Comment by dalathegreat** [comment]
Hi @hugor25 
There is no software for this. I suggest you search the mynissanleaf.com forum for ways to improve range.

Closing this issue, since it is not an issue.
