### ISSUE TITLE
Batterysaver

### ISSUE THREAD

**Issue by nimz77** [dalathegreat/Nissan-LEAF-Battery-Upgrade#22]
Im trying to find battery saver function, looks like it’s not available, are there any alternative way of managing charging limit upto 60%? 

I have applied new firmware with my aze0, it allows to limit at 80% using vehicle function.

thank you very much for supporting ev users.

**Comment by dalathegreat** [comment]
@nimz77 See https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/issues/6 , closing this
