### ISSUE TITLE
Leaf 2018 40kWh -> 62kWh can problem

### ISSUE THREAD

**Issue by 00gtw00** [dalathegreat/Nissan-LEAF-Battery-Upgrade#39]
Hello everyone. I have decided to upgrade the battery in my 2018 Leaf from 40kWh to 62kWh. The car charges with AC and drives without any issues, but it does not charge on fast DC chargers. It shows errors in EV/HEV U1009 and in HV BATTERY P30E0. I found a Nissan technical bulletin stating that the U1009 error appeared in Nissans with a 40kWh battery and that an update of the EV/HEV module software, also known as VCM, should be performed. However, fast charging worked with the 40kWh battery. Could the communication problem be caused by differences in the CAN protocol? Has anyone used a CAN BRIDGE with the new Nissan Leaf?

![Zdjęcie WhatsApp 2024-07-30 o 13 33 47_fb0bdaee](https://github.com/user-attachments/assets/e3133533-9a00-4420-b8e4-41ff18dc27b4)

**Comment by dalathegreat** [comment]
Which CAN bridge software version are you on?

**Comment by 00gtw00** [comment]
I haven't installed the CAN BRIDGE yet. I thought that in the LEAF ZE1, the battery could be replaced with a larger one without it. So, will the CAN BRIDGE be necessary in this case?

**Comment by dalathegreat** [comment]
CAN bridge is needed for safe upgrade. Please install one.

**Comment by 00gtw00** [comment]
So, your firmware for the blue board won't work in this case? It only works for ZE0 and AZE0? 

If you'd like, we can work on this together.

**Comment by marcucci-consulting** [comment]
Same issue with a US market 2018 ZE1 and 62kWh pack from a 2022, but only the P30E0. Haven't tried fast charging yet but I noticed the est charging times (except my single/preferred after key-off) are blank on my dash. We are an edge case but I'd like to sort this out. Haven't poked around the code much. It looks like the 40/62 has the same 8 byte msg for the MY_LEAF_xxxx determination... but @dalathegreat it sounds like you say the bridge won't work in the 2018? I have one in my 2015 I've swapped to 40kWh but not in my 2018 yet.

**Comment by dalathegreat** [comment]
@marcucci-consulting That is correct. All the code in this repository is reformatting battery messages to suit either the ZE0 2011-2012 format, or the AZE0 2013-2017 format. There is no functionality at all for 2018+ LEAFs, so for this I still recommend getting the EVs Enhanced bridge.

If you want to develop a solution for this, we will need CAN logs from a 2018 40kWh, and compare the differences with a CAN log from a 2019+ 62kWh. I have log files available for the [62kWH here](https://github.com/dalathegreat/EV-CANlogs/tree/main/Nissan%20LEAF/62kWh)

**Comment by programuotojasgf** [comment]
I have a Nissan leaf ZE1 with 40kWh battery. How to provide the can logs you mentioned? Can I get them using leaf spy pro or what other way would you recommend?

**Comment by dalathegreat** [comment]
@programuotojasgf 

## Hardware for logging
You will first have to get some hardware capable of reading the communication. Here are some examples, listed from least expensive to more expensive. Do note that more expensive tools will be easier to use, since the software provided with the tools are very user friendly. Also more expensive tools will have better timing and accuracy on timestamps.

    USBCAN PCAN clone 💲 Recommended,link: https://www.aliexpress.us/item/1005006341852788.html 
    Raspberry PI with CAN shield 💲💲
    USB2CAN Korlan 💲💲 Recommended, link: https://www.8devices.com/products/usb2can_korlan 
    Kvaser 💲💲💲
    Peak PCAN 💲💲💲
    Softing 💲💲💲

## Where to connect
The EV-CAN bus required is unfortunately not available in the OBD2 port.

You will need to connect to the EV-CAN bus at the footwell kickpanel. This video shows where the CAN wires are located, twisted pair Blue and Green: https://youtu.be/eLcNSo2Vn6U?si=K5lsO4kkh-_bNav0&t=75

## How to log
Depending on which adapter you got, the logging program varies. Google will help narrow this down.

**Comment by programuotojasgf** [comment]
I really appreciate the response.

The USB2CAN Korlan tool you mentioned connects to the OBD2 port. But you're saying it can not be avoided. Clarification - can it be avoided if I used a more expensive tool? I would best like to avoid splicing if possible. I also found this Y connector -> https://www.diagauto.lt/en/produktas/nissan-1632pin-bypass-secure-gateway-kabelis/ . Would that allow me to read the can bus messages without phisically splicing?

The video shows a gen 1 leaf. Mine is a gen 2 leaf.

**Comment by DevThunder25** [comment]
Hello Dala,

I have purchased the USBCAN PCAN clone and connected to the Green and Blue cables in the foot well. Can you tell me what the settings should be for this application called PCAN-View? it's the app that came with the product. See Attached image: 

<img width="1425" height="978" alt="Image" src="https://github.com/user-attachments/assets/67d0afbc-cbde-40d8-9f9f-a93aecca37dc" />

**Comment by dalathegreat** [comment]
@DevThunder25 , use 500kbps in the "database entry"

**Comment by DevThunder25** [comment]
Dala,

Here are the logs of quick charging in ZE1. Change the file extension back to .trc if necessary. 

Thanks

[ZE1-Trace-QuickCharge.txt](https://github.com/user-attachments/files/27491092/ZE1-Trace-QuickCharge.txt)

**Comment by dalathegreat** [comment]
Nice @DevThunder25 , was this a stock ZE1? Or was it a battery upgraded vehicle?

**Comment by DevThunder25** [comment]
This is a 2018 Nissan leaf that had its battery replaced my Nissan. I was at around 95,000 miles just under warranty expiration. I took it in and showed them that the battery was extremely degraded and they replaced it at no charge.

**Comment by DevThunder25** [comment]
My question to you is with this generation of leaf can I use that older firmware that you mentioned above to achieve the limitation on quick charge speed? My goal is to simply use the CAN bridge to limit the speed at which I charge at a quick charging station.

**Comment by dalathegreat** [comment]
None.

If you want to limit quick charge speed, you can do it this way on a custom code

case 0x1DC:
                    if (QC25kWlimiter) // We want 25kW max
                    {
                        temp2 = 70; // 70A
                        temp2 *= 20;
                        if (qc_power > temp2)
                        {
                            qc_power = temp2;
                        }
                    }
                    else if (QC35kWlimiter) // We want 35kW max
                    {
                        temp2 = 90; // 90A
                        temp2 *= 20;
                        if (qc_power > temp2)
                        {
                            qc_power = temp2;
                        }
                    }
                    else
                    {
                        // No rapidgatedodger active
                      break;
                    }
                    frame->data[2] = (frame->data[2] & 0xF0) | ((qc_power >> 8) & 0xF);
                    frame->data[3] = (uint8_t)(qc_power & 0xFF);
                  calc_crc8(frame);
                  break;

**Comment by babyjohnfan-lgtm** [comment]
So if i understand correctly, we have to allocate the bytes that contain info about how much power the battery is willing to accept and change it? Your code is from rdd but i guess it wont work on its own, right? what do we have to add to it?
