### ISSUE TITLE
 battery percentage shows N/A

### ISSUE THREAD

**Issue by westsince2001** [dalathegreat/Nissan-LEAF-Battery-Upgrade#7]
Unable to display battery percentage after refreshing the latest hex。how to fix？
<img width="188" alt="image" src="https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/assets/4981629/d2f12d3d-e926-4c97-ad0e-d45003b5937d">

**Comment by dalathegreat** [comment]
@westsince2001 What vehicle? (LEAF/env200)? What generation? (ZE0, AZE0, ZE1)? What file did you flash?

**Comment by westsince2001** [comment]
> @westsince2001 What vehicle? (LEAF/env200)? What generation? (ZE0, AZE0, ZE1)? What file did you flash?

AZE0,MD5 (can-bridge-firmware.hex) = 04ad55d8089029b8834f2799d8125cc3

**Comment by dalathegreat** [comment]
@westsince2001 try this file
[can-bridge-firmware.zip](https://github.com/dalathegreat/Nissan-LEAF-Battery-Upgrade/files/12649904/can-bridge-firmware.zip)

**Comment by westsince2001** [comment]
@dalathegreat Tks,i'll try it! ^_^
